### ISSUE TITLE
"panic: newosproc: not implemented" when executing in travis

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [agnivade/wasmbrowsertest#16] opened 2020-02-21 03:06 UTC
I may be doing something stupid, but perhaps someone else has seen this already: 
```
$ GOOS=js GOARCH=wasm go test -exec wasmbrowsertest -v .

panic: newosproc: not implemented

fatal error: panic on system stack

runtime stack:

runtime.throw(0x525ee, 0x15)

	/home/travis/.gimme/versions/go/src/runtime/panic.go:1112 +0x7

panic(0x1df20, 0x71620)

	/home/travis/.gimme/versions/go/src/runtime/panic.go:893 +0x95

runtime.newosproc(...)

	/home/travis/.gimme/versions/go/src/runtime/os_js.go:116

runtime.newm1(0x440000)

	/home/travis/.gimme/versions/go/src/runtime/proc.go:1753 +0x17

runtime.newm(0x58540, 0x430800)

	/home/travis/.gimme/versions/go/src/runtime/proc.go:1732 +0xc

runtime.startm(0x0, 0x100000001)

	/home/travis/.gimme/versions/go/src/runtime/proc.go:1869 +0x1b

runtime.wakep()

	/home/travis/.gimme/versions/go/src/runtime/proc.go:1953 +0x4

runtime.newproc1(0x58430, 0x43c750, 0x0, 0x400180, 0x120e0002)

	/home/travis/.gimme/versions/go/src/runtime/proc.go:3487 +0x4d

runtime.newproc.func1()

	/home/travis/.gimme/versions/go/src/runtime/proc.go:3381 +0x2

runtime.systemstack(0x205a00)

	/home/travis/.gimme/versions/go/src/runtime/asm_wasm.s:166 +0x2

runtime.mstart()

	/home/travis/.gimme/versions/go/src/runtime/proc.go:1041

goroutine 1 [running]:

runtime.systemstack_switch()

	/home/travis/.gimme/versions/go/src/runtime/asm_wasm.s:177 fp=0x43c700 sp=0x43c6f8 pc=0x13b30000

runtime.newproc(0x0, 0x58430)

	/home/travis/.gimme/versions/go/src/runtime/proc.go:3380 +0x3 fp=0x43c740 sp=0x43c700 pc=0x125e0003

runtime.init.5()

	/home/travis/.gimme/versions/go/src/runtime/proc.go:242 +0x2 fp=0x43c758 sp=0x43c740 pc=0x120e0002

runtime.doInit(0x1c8280)

	/home/travis/.gimme/versions/go/src/runtime/proc.go:5414 +0xf fp=0x43c788 sp=0x43c758 pc=0x1288000f

runtime.main()

	/home/travis/.gimme/versions/go/src/runtime/proc.go:150 +0xf fp=0x43c7e0 sp=0x43c788 pc=0x120c000f

runtime.goexit()

	/home/travis/.gimme/versions/go/src/runtime/asm_wasm.s:428 +0x1 fp=0x43c7e8 sp=0x43c7e0 pc=0x13dc0001

FAIL	github.com/WIZARDISHUNGRY/wasm_websocket	0.582s

FAIL

The command "GOOS=js GOARCH=wasm go test -exec wasmbrowsertest -v ." exited with 1.

```

**Comment by agnivade** [comment] 2020-02-21 04:05
You are not doing anything stupid, and yes I have seen this already. https://travis-ci.community/t/goos-js-goarch-wasm-go-run-fails-panic-newosproc-not-implemented/1651.

One hack is to install Go by yourself as mentioned in the link.

In any case, it's not a bug in wasmbrowsertest. I had to stop testing in travis myself due to this bug. Closing.

**Closed by agnivade** 2020-02-21 04:05 UTC
